name: NoAutoCrafter
version: '1.3.0'
main: de.chaosschwein.autocrafter.main.AutoMain
api-version: '1.20'
authors: [ ChaosSchwein, Erik05Master ]
description: Minecraft AutoCrafter Plugin
website: https://sytxlabs.eu

commands:
  autocrafter:
    usage: /autocrafter
    description: AutoCrafter Command
    aliases: [ ac ]
  receiver:
    usage: /receiver
    description: Receiver Command
    aliases: [ rc ]
  sender:
    usage: /sender
    description: Sender Command
    aliases: [ sc ]
  chunkloader:
    usage: /chunkloader
    description: ChunkLoader Command
    aliases: [ cl ]